"""
Training script for the Layer 1 YOLOv8 detection model.

Fine-tunes YOLOv8 on:
  - COCO 2017 person images
  - Open Images V7 Sink + Soap dispenser images

Prepared by: python scripts/prepare_detection_data.py

Run (GPU, recommended):
    python src/handwash/detection/train.py \\
        --data config/detection_data.yaml \\
        --weights yolov8n.pt \\
        --epochs 50 --batch 16 --device 0

Run (CPU / quick sanity check):
    python src/handwash/detection/train.py \\
        --data config/detection_data.yaml \\
        --weights yolov8n.pt \\
        --epochs 3 --batch 4 --device cpu --imgsz 320

After training, copy the best weights:
    cp runs/detection/exp/weights/best.pt models/weights/yolov8_detection.pt
"""

import argparse
import shutil
from pathlib import Path

from ultralytics import YOLO


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Train YOLOv8 detection model (person / sink / soap_dispenser)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--data",
        default="config/detection_data.yaml",
        help="Path to dataset YAML (generated by prepare_detection_data.py)",
    )
    p.add_argument(
        "--weights",
        default="yolov8n.pt",
        help="Starting weights. 'yolov8n.pt' downloads COCO-pretrained nano automatically. "
             "Use 'yolov8s.pt' for better accuracy at the cost of speed.",
    )
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument(
        "--imgsz", type=int, default=640,
        help="Input image size. Must match config.yaml detection.input_size.",
    )
    p.add_argument(
        "--batch", type=int, default=16,
        help="Batch size. Reduce to 8 or 4 if GPU OOM.",
    )
    p.add_argument(
        "--device", default="0",
        help="GPU index (e.g. '0') or 'cpu'. Use '0,1' for multi-GPU.",
    )
    p.add_argument("--project", default="runs/detect", help="Output root directory — ultralytics saves to {project}/{name}/weights/")
    p.add_argument("--name", default="exp", help="Run name (subfolder under --project)")
    p.add_argument(
        "--freeze", type=int, default=0,
        help="Freeze first N layers (0 = train all). Useful to preserve COCO person weights. "
             "Try --freeze 10 for faster fine-tuning.",
    )
    p.add_argument(
        "--copy-weights",
        action="store_true",
        help="After training, copy best.pt → models/weights/yolov8_detection.pt automatically.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    print(f"Starting weights : {args.weights}")
    print(f"Dataset          : {args.data}")
    print(f"Epochs           : {args.epochs}")
    print(f"Image size       : {args.imgsz}")
    print(f"Batch size       : {args.batch}")
    print(f"Device           : {args.device}")
    print(f"Freeze layers    : {args.freeze}")
    print()

    model = YOLO(args.weights)

    results = model.train(
        data=args.data,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        project=args.project,
        name=args.name,
        freeze=args.freeze if args.freeze > 0 else None,
        # Augmentation — important for hospital domain generalisation
        hsv_h=0.015,        # hue shift (handles varying lighting)
        hsv_s=0.7,          # saturation shift
        hsv_v=0.4,          # brightness shift (dim corridors, bright bathrooms)
        fliplr=0.5,         # horizontal flip
        mosaic=1.0,         # mosaic augmentation
        mixup=0.1,          # mixup
        degrees=5.0,        # mild rotation (cameras aren't perfectly level)
        translate=0.1,
        scale=0.5,
    )

    # Ultralytics prepends 'runs/detect/' to the project path automatically
    best_weights = results.save_dir / "weights" / "best.pt"
    print(f"\nTraining complete.")
    print(f"Best weights: {best_weights}")

    if args.copy_weights:
        dest = Path("models/weights/yolov8_detection.pt")
        dest.parent.mkdir(parents=True, exist_ok=True)  # create models/weights/ if missing
        shutil.copy2(best_weights, dest)
        print(f"Copied → {dest}")
    else:
        print(f"\nTo deploy, run:")
        print(f"  cp {best_weights} models/weights/yolov8_detection.pt")


if __name__ == "__main__":
    main()
